#!/usr/bin/env python3
"""
HTML Presentation to MP4 Video Converter

This tool records an HTML presentation (like those generated by the Storyteller agent)
into an MP4 video file. It uses Playwright to capture the slides and ffmpeg to
convert the recording to a high-quality MP4.

Requirements:
    uv tool install playwright
    uvx playwright install chromium
    ffmpeg (installed on system path)

Usage:
    uv run --with playwright tools/html2video.py input.html output.mp4 [--duration 5]
"""

import asyncio
import argparse
import sys
import shutil
import tempfile
import subprocess
from pathlib import Path

# Check for Playwright availability
try:
    from playwright.async_api import async_playwright
except ImportError:
    print("Error: 'playwright' package is not installed.")
    print("Please run with uv:")
    print("    uv run --with playwright tools/html2video.py ...")
    print("Or install browsers if needed:")
    print("    uvx playwright install chromium")
    sys.exit(1)

def check_dependencies():
    """Verify that external dependencies are available."""
    # Check for ffmpeg
    if not shutil.which('ffmpeg'):
        print("Error: 'ffmpeg' is not found on the system path.")
        print("Please install ffmpeg to use this tool.")
        sys.exit(1)

async def record_presentation(html_path: str, output_path: str, duration: float, width: int, height: int):
    """
    Record an HTML presentation to video.
    
    Args:
        html_path: Path to the input HTML file
        output_path: Path for the output MP4 file
        duration: Duration to show each slide in seconds
        width: Video width
        height: Video height
    """
    # Ensure input file exists
    input_file = Path(html_path).resolve()
    if not input_file.exists():
        print(f"Error: Input file '{html_path}' not found.")
        sys.exit(1)

    print(f"Preparing to record '{input_file.name}'...")
    print(f"Settings: {width}x{height}, {duration}s per slide")

    # Create a temporary directory for the raw recording
    with tempfile.TemporaryDirectory() as temp_dir:
        temp_path = Path(temp_dir)
        
        async with async_playwright() as p:
            # Launch browser
            browser = await p.chromium.launch(headless=True)
            
            # Create a context with video recording enabled
            # record_video_size must match the viewport size for best results
            context = await browser.new_context(
                viewport={"width": width, "height": height},
                record_video_dir=str(temp_path),
                record_video_size={"width": width, "height": height}
            )
            
            page = await context.new_page()
            
            # Navigate to the file
            # Using file:// URL
            url = f"file://{input_file}"
            print("Loading presentation...")
            await page.goto(url)
            
            # Wait for content to load
            await page.wait_for_load_state("networkidle")
            
            # Count slides
            # Assuming standard Storyteller HTML structure with .slide class
            # or reveal.js structure. We'll try a generic approach first.
            # If standard Storyteller format (Apple Keynote style), slides are likely 
            # elements that are navigated through.
            
            # For the purpose of this tool, we assume a simple click-to-advance mechanism
            # or just timing based on visual slide elements.
            # Let's count elements with class "slide" if they exist
            slide_count = await page.locator('.slide').count()
            
            if slide_count == 0:
                # Fallback: maybe it's not using .slide class. 
                # Just record for a fixed duration? 
                # Or assume at least 1 "view" and we just capture what's there.
                print("Warning: No elements with class '.slide' found. Recording single view.")
                slide_count = 1
            else:
                print(f"Found {slide_count} slides.")
            
            print("Recording started...")
            
            # Iterate through slides
            for i in range(slide_count):
                sys.stdout.write(f"\rRecording slide {i+1}/{slide_count}...")
                sys.stdout.flush()
                
                # Wait for the duration of the slide
                await asyncio.sleep(duration)
                
                # Advance to next slide
                if i < slide_count - 1:
                    await page.keyboard.press('ArrowRight')
                    # Small buffer for transition if any
                    await asyncio.sleep(0.5)
            
            print("\nRecording finished. Processing...")
            
            # Close context to save the video
            await context.close()
            await browser.close()
            
            # Find the recorded video file (Playwright generates a random name)
            # It should be the only .webm file in the temp dir
            video_files = list(temp_path.glob("*.webm"))
            if not video_files:
                print("Error: No video file was generated by Playwright.")
                sys.exit(1)
                
            raw_video = video_files[0]
            
            # Convert to MP4 using ffmpeg
            print(f"Converting to MP4: {output_path}")
            
            # ffmpeg command:
            # -y: Overwrite output
            # -i: Input file
            # -c:v libx264: H.264 codec
            # -pix_fmt yuv420p: Pixel format for compatibility
            cmd = [
                'ffmpeg',
                '-y',
                '-v', 'error',  # Suppress output unless error
                '-i', str(raw_video),
                '-c:v', 'libx264',
                '-pix_fmt', 'yuv420p',
                str(output_path)
            ]
            
            try:
                subprocess.run(cmd, check=True)
                print(f"Success! Video saved to {output_path}")
            except subprocess.CalledProcessError as e:
                print(f"Error converting video: {e}")
                sys.exit(1)

def main():
    parser = argparse.ArgumentParser(description="Convert HTML presentation to MP4 video.")
    parser.add_argument("input_file", help="Path to input HTML file")
    parser.add_argument("output_file", help="Path to output MP4 file")
    parser.add_argument("--duration", type=float, default=5.0, help="Duration per slide in seconds (default: 5.0)")
    parser.add_argument("--width", type=int, default=1920, help="Video width (default: 1920)")
    parser.add_argument("--height", type=int, default=1080, help="Video height (default: 1080)")
    
    args = parser.parse_args()
    
    check_dependencies()
    
    try:
        asyncio.run(record_presentation(
            args.input_file,
            args.output_file,
            args.duration,
            args.width,
            args.height
        ))
    except KeyboardInterrupt:
        print("\nOperation cancelled by user.")
        sys.exit(1)
    except Exception as e:
        print(f"\nUnexpected error: {e}")
        sys.exit(1)

if __name__ == "__main__":
    main()
